version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cicd
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/cicd
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
